// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQCATdcyf15lQBwrrdSuD417zM6rMhmBg',
    appId: '1:308482841964:web:048f8ac6b3678ef66b6749',
    messagingSenderId: '308482841964',
    projectId: 'ta3dia',
    authDomain: 'ta3dia.firebaseapp.com',
    storageBucket: 'ta3dia.firebasestorage.app',
    measurementId: 'G-BMT930FJY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2zzvmEP77k3xQkojNozHFayYoYijtBCQ',
    appId: '1:308482841964:android:0b662f4ca36121506b6749',
    messagingSenderId: '308482841964',
    projectId: 'ta3dia',
    storageBucket: 'ta3dia.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMFoTQCqgXF5SKdnLcPw4KSkV-eperTXc',
    appId: '1:308482841964:ios:d06c3de79b237ead6b6749',
    messagingSenderId: '308482841964',
    projectId: 'ta3dia',
    storageBucket: 'ta3dia.firebasestorage.app',
    iosClientId:
        '308482841964-j6svl9c4tdan53noh65eahvg9fodhmvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.ta3dia',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMFoTQCqgXF5SKdnLcPw4KSkV-eperTXc',
    appId: '1:308482841964:ios:d06c3de79b237ead6b6749',
    messagingSenderId: '308482841964',
    projectId: 'ta3dia',
    storageBucket: 'ta3dia.firebasestorage.app',
    iosBundleId: 'com.example.ta3dia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQCATdcyf15lQBwrrdSuD417zM6rMhmBg',
    appId: '1:308482841964:web:048f8ac6b3678ef66b6749',
    messagingSenderId: '308482841964',
    projectId: 'ta3dia',
    authDomain: 'ta3dia.firebaseapp.com',
    storageBucket: 'ta3dia.firebasestorage.app',
    measurementId: 'G-BMT930FJY2',
  );
}
