// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFiB2XWbBiE0lA3mRWC0d1dANIUcoOs6k',
    appId: '1:943981493524:web:placeholder',
    messagingSenderId: '943981493524',
    projectId: 'ta3dia2',
    authDomain: 'ta3dia2.firebaseapp.com',
    storageBucket: 'ta3dia2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFiB2XWbBiE0lA3mRWC0d1dANIUcoOs6k',
    appId: '1:943981493524:android:07045932fa2ce312529601',
    messagingSenderId: '943981493524',
    projectId: 'ta3dia2',
    storageBucket: 'ta3dia2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFiB2XWbBiE0lA3mRWC0d1dANIUcoOs6k',
    appId: '1:943981493524:ios:placeholder',
    messagingSenderId: '943981493524',
    projectId: 'ta3dia2',
    storageBucket: 'ta3dia2.firebasestorage.app',
    iosBundleId: 'com.example.ta3dia2',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFiB2XWbBiE0lA3mRWC0d1dANIUcoOs6k',
    appId: '1:943981493524:macos:placeholder',
    messagingSenderId: '943981493524',
    projectId: 'ta3dia2',
    storageBucket: 'ta3dia2.firebasestorage.app',
    iosBundleId: 'com.example.ta3dia2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFiB2XWbBiE0lA3mRWC0d1dANIUcoOs6k',
    appId: '1:943981493524:web:placeholder',
    messagingSenderId: '943981493524',
    projectId: 'ta3dia2',
    authDomain: 'ta3dia2.firebaseapp.com',
    storageBucket: 'ta3dia2.firebasestorage.app',
  );
}
